# Generated by Django 3.0.5 on 2020-06-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marqueeHeading', models.CharField(default='', max_length=50)),
                ('heading', models.CharField(max_length=100)),
                ('pdf', models.FileField(default='', upload_to='pdf')),
                ('datePublished', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('unit_test_1', 'Unit test 1'), ('unit_test_2', 'Unit test 2'), ('semister_1', 'Semister 1'), ('unit_test_3', 'Unit test 3'), ('unit_test_4', 'Unit test 4'), ('semister_2', 'Semister 2')], default='Semister 1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearname', models.CharField(default='', max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.School')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('obtained_marks', models.IntegerField(default=0, max_length=4)),
                ('total_marks', models.IntegerField(default=0, max_length=4)),
                ('result', models.ForeignKey(default='Semister_1', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(default='', max_length=50)),
                ('standard', models.IntegerField(choices=[(5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th')], default=5)),
                ('divison', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(default='2018', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Year')),
            ],
        ),
    ]
