# Generated by Django 3.0.5 on 2020-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='obtained_marks',
            field=models.IntegerField(default=0),
        ),
    ]
