# Generated by Django 3.0.5 on 2020-06-30 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Drawing',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='English',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='Hindi',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='ICT',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='Marathi',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='Mathematics',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='Maximum_marks_for_each_subject',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='PE',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='Science',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='SocialScience',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=20), message='cannot be more than<django.db.models.fields.IntegerField>')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.IntegerField(choices=[(5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th')], default=5),
        ),
    ]
