# Generated by Django 3.0.5 on 2020-06-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200630_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenth_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], default='2020-21', max_length=10)),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='Drawing',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='English',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='Hindi',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='ICT',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='Marathi',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='Mathematics',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='PE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='Science',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='SocialScience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Tenth_Topper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('percentage', models.SmallIntegerField(default=100)),
                ('tenth_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tenth_Result')),
            ],
        ),
    ]
