# Generated by Django 3.0.5 on 2020-06-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200628_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='subheading',
        ),
        migrations.AddField(
            model_name='notice',
            name='marqueeHeading',
            field=models.CharField(default='', max_length=50),
        ),
    ]
