# Generated by Django 3.0.5 on 2020-06-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200630_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenth_topper',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
