# Generated by Django 3.0.5 on 2020-06-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20200628_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='datePublished',
            field=models.DateTimeField(),
        ),
    ]
