# Generated by Django 3.0.5 on 2020-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_tenth_topper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenth_result',
            name='year',
            field=models.CharField(choices=[('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], default='2020-21', max_length=10, unique=True),
        ),
    ]
