# Generated by Django 3.0.5 on 2020-07-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20200630_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField()),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('father_occupation', models.CharField(max_length=20)),
                ('parent_contact_1', models.IntegerField(default=1234567890)),
                ('parent_contact_2', models.IntegerField(default=1234567890)),
                ('temporary_address', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='media/images')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student')),
            ],
        ),
    ]
