# Generated by Django 3.0.5 on 2020-07-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permenant_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
