# Generated by Django 3.0.5 on 2020-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=10),
        ),
    ]
