# Generated by Django 3.0.5 on 2020-07-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_homework_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=20),
        ),
    ]
