# Generated by Django 3.0.5 on 2020-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20200701_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
